apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: robokart 
  labels:
    name: payment
    project: robokart
    tier: app 
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels: # deployment-set labels
      name: payment
      project: robokart
      tier: app
  template: # pod defination
    metadata:
      labels: # pod labels
        name: payment
        project: robokart
        tier: app
    spec:
      containers:
      - name: payment
        image: iamroyalreddy/payment:{{ .Values.deployment.imageVersion }}
        imagePullPolicy: {{ .Values.deployment.imagePullPolicy }}
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "100m"  
        envFrom:
        - secretRef:
            name: payment