apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: robokart
  labels: # deployment-set labels
    name: nginx
    app: frontend
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels: # deployment-set labels
      name: nginx
      app: frontend
  template: # pod defination
    metadata:
      labels: # pod labels
        name: nginx
        app: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:{{ .Values.deployment.imageVersion }}
        imagePullPolicy: Always
        resources:
          requests:
            memory: "256Mi"
            cpu: "300m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
            - containerPort: 80      
