apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: robokart 
  labels:
    name: user
    project: robokart
    tier: app 
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels: # deployment-set labels
      name: user
      project: robokart
      tier: app
  template: # pod defination
    metadata:
      labels: # pod labels
        name: user
        project: robokart
        tier: app
    spec:
      containers:
      - name: user
        image: iamroyalreddy/user:{{ .Values.deployment.imageVersion }}
        imagePullPolicy: {{ .Values.deployment.imagePullPolicy }}
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "100m"  
        envFrom:
        - configMapRef:
            name: user