apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: robokart 
  labels:
    name: shipping
    project: robokart
    tier: app 
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels: # deployment-set labels
      name: shipping
      project: robokart
      tier: app
  template: # pod defination
    metadata:
      labels: # pod labels
        name: shipping
        project: robokart
        tier: app
    spec:
      containers:
      - name: shipping
        image: iamroyalreddy/shipping:{{ .Values.deployment.imageVersion }}
        imagePullPolicy: {{ .Values.deployment.imagePullPolicy }}
        resources:
          requests:
            memory: "256Mi"
            cpu: "150m"
          limits:
            memory: "512Mi"
            cpu: "300m"  
        envFrom:
        - configMapRef:
            name: shipping