apiVersion: v1
kind: Secret
metadata:
  name: mysql
  namespace: robokart 
  labels:
    name: mysql
    project: robokart
    app: db
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: Um9ib1Nob3BAMQ==
  MYSQL_PASSWORD: Um9ib1Nob3BAMQ==
  MYSQL_USER: c2hpcHBpbmc= 