apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: robokart 
  labels:
    name: mysql
    project: robokart
    app: db
spec:
  ports:
  - port: 27017
    name: mysql
  clusterIP: None
  selector:
    name: mysql
    project: robokart
    app: db