apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq
  namespace: robokart
  labels:
    name: rabbitmq
    project: robokart
    app: db
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: cm9ib3Nob3A=
  RABBITMQ_DEFAULT_PASS: cm9ib3Nob3AxMjM=