apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: robokart 
  labels:
    name: rabbitmq
    project: robokart
    app: db
spec:
  ports:
  - port: 27017
    name: rabbitmq
  clusterIP: None
  selector:
    name: rabbitmq
    project: robokart
    app: db