apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: robokart 
  labels:
    name: mongodb
    project: robokart
    app: db
spec:
  ports:
  - protocol: TCP
    port: 27017 #service-port
    targetPort: 27017
  clusterIP: None
  selector:
    name: mongodb
    project: robokart
    app: db