apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: robokart 
  labels:
    name: mongodb
    project: robokart
    app: db
spec:
  ports:
  - port: 27017
    name: mongodb
  clusterIP: None
  selector:
    name: mongodb
    project: robokart
    app: db