apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: robokart 
  labels:
    name: web
    project: robokart
    tier: app 
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels: # deployment-set labels
      name: web
      project: robokart
      tier: app
  template: # pod defination
    metadata:
      labels: # pod labels
        name: web
        project: robokart
        tier: app
    spec:
      containers:
      - name: web
        image: iamroyalreddy/web:{{ .Values.deployment.imageVersion }}
        imagePullPolicy: {{ .Values.deployment.imagePullPolicy }}
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "100m"  
        volumeMounts:
          - name: nginx-conf
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
            readOnly: true 
      volumes:
      - name: nginx-conf
        configMap:
            name: web
            items:
              - key: nginx.conf
                path: nginx.conf   